# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JW3Xx6xVW3r_rSh-HZXCc84KlNNBrM8
"""

import streamlit as st
import requests
from bs4 import BeautifulSoup
st.title("Website Title Scraper")
url = st.text_input("https://xnxx.health/search/xnxx")
if st.button("Scrape Title") and url:
    response = requests.get(url, timeout=10)
    soup = BeautifulSoup(response.text, "html.parser")
    title = soup.title.string if soup.title else "No title found"
    st.write(f"*Website Title:* {title}")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

pip install beautifulsoup4